#!/bin/bash

set -e

PROJECT_DIR=project_a
(cd ${PROJECT_DIR} && VERSION="$(python setup.py --version)")

GITSHA="$(script/build_${PROJECT_DIR}/write-git-sha)"
GITREPO="$(script/build_${PROJECT_DIR}/write-git-repo)"
BUILDDATE="$(script/build_${PROJECT_DIR}/write-build-date)"
COMMITDATE="$(script/build_${PROJECT_DIR}/write-commit-date)"
echo "${GITSHA}" > ${PROJECT_DIR}/BUILD_GITSHA
echo "${GITREPO}" > ${PROJECT_DIR}/BUILD_GITREPO
echo "${BUILDDATE}" > ${PROJECT_DIR}/BUILD_DATE
echo "${COMMITDATE}" > ${PROJECT_DIR}/BUILD_LASTCOMMITDATE

(cd ${PROJECT_DIR} && pip install -r requirement-dev.txt && pip install -r requirement.txt && python setup.py sdist bdist_wheel)

rm -rf ${PROJECT_DIR}/{BUILD_GITSHA,BUILD_GITREPO,BUILD_DATE,BUILD_LASTCOMMITDATE,${PROJECT_DIR}}
