#!/bin/bash

set -e

PROJECT_DIR=project_a

GITSHA="$(script/build_${PROJECT_DIR}/write-git-sha)"
GITREPO="$(script/build_${PROJECT_DIR}/write-git-repo)"
BUILDDATE="$(script/build_${PROJECT_DIR}/write-build-date)"
COMMITDATE="$(script/build_${PROJECT_DIR}/write-commit-date)"
echo "${GITSHA}" > ${PROJECT_DIR}/BUILD_GITSHA
echo "${GITREPO}" > ${PROJECT_DIR}/BUILD_GITREPO
echo "${BUILDDATE}" > ${PROJECT_DIR}/BUILD_DATE
echo "${COMMITDATE}" > ${PROJECT_DIR}/BUILD_LASTCOMMITDATE

(cd ${PROJECT_DIR} && rm -rf build && pyinstaller -F main.py --collect-datas="project_a")

rm -f ${PROJECT_DIR}/{BUILD_GITSHA,BUILD_GITREPO,BUILD_DATE,BUILD_LASTCOMMITDATE,*.spec}

popd 